import { StyleSheet, View } from "react-native";

export const styles = StyleSheet.create({
    backImage:{
        width:'100%',
        height:'100%',
    },
    container:{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    ViewSlogan:{
        position:'absolute',
        top:10,
        left:30,
        width:350,
        paddingTop:100,
    },
    TextSlogan:{
        color:'#000', 
        fontSize:20, 
        fontWeight:'bold',
        width:350,
        textAlign:'center'
    },
    logo:{
        width:80,
        height:80,
    },
    wine:{
        width:300,
        height:600,
    },
    title:{
        color:'#000',
        fontSize:60,
        fontWeight:'bold',
        width:220
    },
    price:{
        color:'#000',
        fontSize:80,
        fontWeight:'bold',
        width:220
    },
    subTitle:{
        fontSize:20,
        width:200
    },
    midView:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
    },
    botao:{
        position:'absolute',
        bottom:20,
        width:100, 
        height:100,
        margin:50
    },
    // Internal Pages
    botaoView:{
        position:'absolute',
        top:120,
        right:-90,
        width:100, 
        height:100,
        margin:50
    },
    ImageTop:{
        width:440,
        height:200,
        borderTopRightRadius:35,
        borderTopLeftRadius:35
    },
    bodyPage:{
        flex:1,
        justifyContent:'flex-start',
        alignItems:'center',
        backgroundColor: '#030445',
        borderRadius:20,
    },
    thumbView:{
        width:'100%',
        paddingVertical:10, 
        paddingHorizontal:50, 
        flexDirection:'row', 
        alignItems:'center',
        gap:12
    },
    thumbImage:{
        width:100, 
        height:100,
        borderWidth:1,
        borderColor:'#fff',
        borderRadius:10
    },
    viewText:{
        flexDirection:'column',
        gap:5
    },
    textDescription:{
        color:'#fff',
        textAlign:'justify',
        paddingVertical:10
    }
})